version = 1

[[analyzers]]
name = "python"
enabled = true
  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "security"
enabled = true
  [analyzers.meta]
  runtime_version = "3.x.x"
